### PR TITLE
Better copyright align

### PR DESCRIPTION
**Pull request by andreiggr**
Better copyright align in Image block with hoverable text over 50 char

### CODE REVIEW

**Review by ichim-david — CHANGES_REQUESTED** [review]
@andreiggr one thing I don't like, to see if you can do something about it.
If I get the popup and I want to copy the text from the copyright the hover
div disappears when right clicking inside it.

**Review by andreiggr — COMMENTED** [review]
Hi @ichim-david @avoinea . Tested on Chrome and Firefox and the copyright text stays on screen to copy/paste the text.

**Comment by ichim-david** [comment]
> Hi @ichim-david @avoinea . Tested on Chrome and Firefox and the copyright text stays on screen to copy/paste the text.
As mentioned on riot the right click still hides the popup on Firefox

**Review by ichim-david — CHANGES_REQUESTED** [review]
@andreiggr during today's meeting, there was a mention of having the mobile behavior where only the copyright sign is visible until you hover or touch the symbol for the copyright not added in the page header

**Review by ichim-david — APPROVED** [review]

**Comment by ichim-david** [comment]
There are still some issues, left:
1. the copyright doesn't show up on M or S image size
2. The block size needs further work due to the moving of size directly to the block made by me

**Review by ichim-david — APPROVED** [review]

**Pull request merged**
